Cold staking
particl/bitcore-wallet-service pull request #4
Opened 2019-02-15 15:29 UTC by spazzymoto

Draft pull request, i need particl-bitcore-lib to be merged so i can update the package-lock.json file

2019-02-21 13:19 UTC, kewde approved these changes
Looks alright to me!

2019-03-25 10:20 UTC, rynomster requested changes
Not sure if you ran the linter? or if there is one :P

2019-03-25 10:20 UTC, rynomster commented on lib/server.js
> +        if (activity)
Best to use our standards, always use `{` curly braces

2019-03-25 10:20 UTC, rynomster commented on lib/server.js
> +        if (_.isEmpty(addresses)) // Only increment when there is any activity on a address derived from this index
same here.. lets stick to the standards

2019-03-25 10:20 UTC, rynomster commented on lib/server.js
> +    // TODO: Wallets with single addresses not sha256 cannot cold stake
Is this just a reminder?

2019-03-25 10:20 UTC, rynomster commented on lib/model/wallet.js
> +  if (self.coin === 'part')
Code standards `{`

2019-03-25 10:22 UTC, rynomster commented
Doesn't look like there is a lint command

2019-03-25 11:08 UTC, rynomster commented on lib/server.js
> +          activeDerivativeIndex = true;
Why not put an else return here? :)

2019-03-25 17:34 UTC, merged